title: Kevin Son – Product Designer
logo:  # you can add own logo.
description: A Designer love food.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sonkd.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Kevin Kim
  image: '/assets/img/profile.jpg'
  job: Product Designer
  bio: I'm a Product Designer love food and living in Hanoi, Vietnam
  email: sonkdbk@gmail.com


# Contact links
contact:
  - name: Twitter
    link: https://twitter.com/KevinSonkd
  - name: Instagram
    link: https://www.instagram.com/kimdinhson/
  - name: Medium
    link: https://medium.com/@sonkd
  - name: Linkedin
    link: https://www.linkedin.com/in/kevinsonkd/
  - name: Github
    link: https://github.com/sonkd


# Comment Section (Disqus)
disqus-identifier: kimdinhson # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: G-Q7TE8E3445 # add your identifier. For example UA-99631805-1.

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-admin
  - jekyll-pagebreak
  - jekyll-seo-tag
  - jekyll/tagging

collections_dir: collections
collections:
  projects:
    output: true
    permalink: /projects/:name
  blog:
    output: true
    permalink: /blog/:name
  research:
    output: true
    permalink: /research/:name

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty


sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
