# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "assets/img/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "collections/_blog/"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: true
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tag", widget: "list" }
      - {
          label: "Cover Image",
          name: "image",
          widget: "image"
        }
      - {
          label: "Author",
          name: "author",
          widget: "string",
          default: "sonkd"
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "project"
    label: "Project"
    folder: "collections/_projects/"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: true
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "case-study" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tag", widget: "list" }
      - {
          label: "Cover Image",
          name: "image",
          widget: "image"
        }
      - {
          label: "Project code",
          name: "showcase-code",
          widget: "string",
          default: "project-00"
        }
      - { label: "Company", name: "company", widget: "text" }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Release Date", name: "project-date", widget: "datetime" }
      - { label: "Challenges description", name: "challenges", widget: "text" }
      - { label: "Role", name: "roles", widget: "list", default: ["Product Design"] }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "page"
    label: "Pages"
    files:
      - label: "About me"
        name: "about"
        file: "_pages/about.md"
        fields:
          - {
              label: "Title",
              name: "title",
              widget: "hidden",
              default: "about",
            }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "post",
            }
          - {
              label: "Image",
              name: "image",
              widget: "image",
              default: "/assets/img/profile.jpg"
            } 
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Archive"
        name: "archive"
        file: "_data/archive-list.yml"
        collapsed: true
        widget: "list"
        fields:
          - label: List
          - widget: object
          - fields:
            - {
              label: "Title",
              name: "title",
              widget: "hidden"
            }
          - { label: "Year", name: "year", widget: "number", default: 2024, value_type: "int" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Description", name: "description", widget: "text" }
          - {
              label: "Image",
              name: "image",
              widget: "image",
            }
          - {
              label: "Alternative text",
              name: "alt",
              widget: "string",
            }
          - {
              label: "Archive Link",
              name: "url",
              widget: "string",
            }